### ISSUE TITLE
关于手势控制的问题

### ISSUE THREAD

**Issue by iotxc** [Vove7/Android-Accessibility-Api#1]
想问博主一个问题，就是我们现在想模拟用户在微信语音聊天中取消发送的操作，但是经过尝试发现这个功能好像实现不了。因为当我们用dispatchGesture模拟长按的操作时，如果这时加了一个上滑的操作那么之前的操作就会在GestureResultCallback被监听到取消了，然后微信那边就直接发送出去了。请问这个有解吗？

**Comment by Vove7** [comment]
执行时手势路径就已经确定了，好像无解

**Comment by iotxc** [comment]
@Vove7 恩恩 好的 谢谢
