### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 79660095** [Vove7/Android-Accessibility-Api#11]
2个问题，经常会遇到弹个框程序无响应，查找我是运行在IO线程里的。还有一个就是 查找的时候会抛出这个RuntimeException("无障碍服务未运行: $name") ，这个不知道是什么引起的

**Comment by Vove7** [comment]
提示无障碍未运行，需要重新开关 无障碍服务。不行的话需要重启手机

**Comment by zongzj** [comment]
> 

重启手机不行吧。要关机-》开机
