### ISSUE TITLE
想问下有Java版本的么

### ISSUE THREAD

**Issue by 704480904** [Vove7/Android-Accessibility-Api#12]
想问下有Java版本的么 因为项目是老项目 都是Java代码，引入新东西的话，担心存在兼容性问题，想问下有Java版本的代码没  或者直接把这份kotlin 代码转成Java代码 会 不会有什么问题

**Comment by Vove7** [comment]
Java其实可以用的，只是姿势有些不方便
。可以看aar包里的Java类 方法列表，当成Java方法来用就行了

**Comment by Vove7** [comment]
引入kt不会有什么兼容问题的

**Comment by 704480904** [comment]
主要是项目是Java代码写的，要把这玩意封装成sdk  ，然后给Python来调用，担心Python无法直接调起来kotlin  ，但是Python调用Java的框架我已经弄好了，所以我是要参考aar里面的Java代码，然后改一个Java版本么，那Java里面没有协程 怎么处理这块的代码呢？
