### ISSUE TITLE
为什么ScreenTextFinder().find()获取到的不是当前界面的，而是旧的界面的元素

### ISSUE THREAD

**Issue by jacknathan** [Vove7/Android-Accessibility-Api#15]
为什么ScreenTextFinder().find()获取到的不是当前界面的，而是之前旧的界面元素？

**Comment by Vove7** [comment]
是否在不同应用的页面也是这样？如果不是，请查看该应用的全部窗口节点信息

**Comment by Vove7** [comment]
@jacknathan  老哥解决了吗。我在三星安卓9.0遇到这样的问题了，返回桌面再进来 才刷新视图信息..
