### ISSUE TITLE
华为出现这种问题 "old interaction Id is: -1"

### ISSUE THREAD

**Issue by 0x6pak** [Vove7/Android-Accessibility-Api#17]
华为荣耀x8
操作节点会不断地出现以下日志
W/AccessibilityInteractionClient: old interaction Id is: -1,current interaction Id is:0
W/AccessibilityInteractionClient: old interaction Id is: -1,current interaction Id is:1
W/AccessibilityInteractionClient: old interaction Id is: -1,current interaction Id is:2
W/AccessibilityInteractionClient: old interaction Id is: -1,current interaction Id is:3
W/AccessibilityInteractionClient: old interaction Id is: -1,current interaction Id is:4
W/AccessibilityInteractionClient: old interaction Id is: -1,current interaction Id is:5
W/AccessibilityInteractionClient: old interaction Id is: -1,current interaction Id is:6

**Comment by Vove7** [comment]
一般是系统日志哈
