### ISSUE TITLE
没法下载依赖包

### ISSUE THREAD

**Issue by pingan8** [Vove7/Android-Accessibility-Api#18]
![image](https://user-images.githubusercontent.com/108533707/224202224-6639d8f4-f324-4baf-bc5e-e79b00bb9f80.png)

**Comment by pingan8** [comment]
![image](https://user-images.githubusercontent.com/108533707/224202361-2dc1239d-cff0-4569-bf3e-747c31e96f25.png)

**Comment by Vove7** [comment]
TAG换成具体版本号
