### ISSUE TITLE
没法点击找不到text

### ISSUE THREAD

**Issue by 5tiaowu** [Vove7/Android-Accessibility-Api#24]
![image](https://user-images.githubusercontent.com/108533707/228510666-3e010502-dbda-4872-80bd-70790237907a.png)

**Comment by pingan8** [comment]
![image](https://user-images.githubusercontent.com/108533707/228510999-81c9e3f9-77b9-452e-8d4d-36c9404f2b56.png)

**Comment by pingan8** [comment]
![image](https://user-images.githubusercontent.com/108533707/228511579-d3872cb9-006d-4b13-a30c-b396b414c570.png)

**Comment by Vove7** [comment]
类型是button，为什么指定textview

**Comment by 5tiaowu** [comment]
明白了因为这个地方没有文档说明所以有点理解模糊
