### ISSUE TITLE
Instrumentation版本Demo如果启动呢

### ISSUE THREAD

**Issue by easysg** [Vove7/Android-Accessibility-Api#30]
Instrumentation版本Demo如果启动呢

**Comment by Vove7** [comment]
adb shell am instrument -w cn.vove7.andro_accessibility_api.demo/.MyInstrumentation

**Comment by zkywalker** [comment]
也就是说想使用uiautomator必须开启开发者模式使用adb？有脱（PC）机的使用uiautomator的方案吗，我想直接用uiautomator dump 页面结构。

**Comment by Krosxx** [comment]
可以借助shizuku

**Comment by Domlaa** [comment]
> adb shell am instrument -w cn.vove7.andro_accessibility_api.demo/.MyInstrumentation



> adb shell am instrument -w cn.vove7.andro_accessibility_api.demo/.MyInstrumentationadb shell am instrument -w cn.vove7.andro_accessibility_api.demo/.我的仪器



> adb shell am instrument -w cn.vove7.andro_accessibility_api.demo/.MyInstrumentation

输入命令后命令行卡住，设备也没变化，请问这个是什么原因呢
