### ISSUE TITLE
获取列表（RecyclerView）的child会使用缓存 该如何解决

### ISSUE THREAD

**Issue by LxzBUG** [Vove7/Android-Accessibility-Api#32]
chatLayout.node.refresh()
 
 还是
 
  chatLayout.node.clearChildrenCache啊

**Comment by Vove7** [comment]
ViewNode.refresh()

**Comment by LxzBUG** [comment]
谢谢

**Comment by Vove7** [comment]
SF.id("chat_message_list").requireFirst().refresh()

**Comment by LxzBUG** [comment]
SF.id("chat_message_input").findFirst()
 
 为什么有时候 明明在当前页面 有这个view 就是找不到呢 
 
 fun sendHiContent() {
        lifecycleScope.launch {
            delay(onceDelay)
            SF.id("chat_message_input").findFirst()?.let { chat_message_input->
                chat_message_input.text = getHiContent()
                delay(onceDelay)
                Log("发送打招呼信息")
                SF.id("send_btn").findFirst()?.let { btnSend->
                    btnSend.tryClick()
                    delay(onceDelay)
                    Log("发送成功，返回首页")
                    backHome()
                }
            }?:let {
                startJob()
            }
        }
    }

**Comment by LxzBUG** [comment]
```kotlin  fun sendHiContent() {
        lifecycleScope.launch {
            delay(onceDelay)
            SF.id("chat_message_input").findFirst()?.let { chat_message_input->
                chat_message_input.text = getHiContent()
                delay(onceDelay)
                Log("发送打招呼信息")
                SF.id("send_btn").findFirst()?.let { btnSend->
                    btnSend.tryClick()
                    delay(onceDelay)
                    Log("发送成功，返回首页")
                    backHome()
                }
            }?:let {
                startJob()
            }
        }
    }```
