### ISSUE TITLE
exist()一直返回false

### ISSUE THREAD

**Issue by topcoco** [Vove7/Android-Accessibility-Api#39]
<img width="337" alt="image" src="https://github.com/Krosxx/Android-Auto-Api/assets/108533707/90df654d-256d-4aa2-b0e5-3ab6dd5af045">
<img width="188" alt="image" src="https://github.com/Krosxx/Android-Auto-Api/assets/108533707/e7375e21-f0df-4fe8-938c-2f3345fd9227">
这个自己创建搜索条件返回的好想没法用这个来判断是否存在节点一直是false

**Comment by 0cococ** [comment]
s[0].finder().exist()
